### ISSUE TITLE
Netlify is detected as Deno

### ISSUE THREAD

**Issue by cyco130** [QuiiBz/detect-runtime#2]
As seen in [here](https://64a837ff1a4298118d07c1ca--hattip-netlify-template.netlify.app/edge-runtime) currently the runtime for the Netlify Edge Functions is detected as Deno.

It is indeed based on Deno so the `typeof Deno` check returns truthy. Changing the order of checks will probably fix it.

**Comment by QuiiBz** [comment]
Good catch. I started working on https://github.com/QuiiBz/detect-runtime/pull/1 to make sure everything is detected as expected.

**Comment by QuiiBz** [comment]
Should be fixed in [1.0.1](https://github.com/QuiiBz/detect-runtime/releases/tag/1.0.1). Thanks!
